Install and instantiate simple urql client capable of server side rendering
Installed fastify-cors to accept all requests from localhost, will have to be changed when deploying

The following can be used to make a page use server side rendering:
export async function getStaticProps() {
  await client.query(usersQuery).toPromise();
  return( { props: { urqlState: ssrCache.extractData() } })
}

With the current setup, server side rendering gives the following error which is solved by not returning an error in CORS:
Error: Error serializing `.urqlState["1612234747"].error.graphQLErrors[0].path` returned from `getStaticProps` in "/".

Temporarily removed @auth directives from the schema until I implement login and auth in the frontend

Followed instructions on https://www.youtube.com/watch?v=Miock1yWkCQ